# Solveurs directs

Les solveurs directs reposent sur l'observation que trois types de
matrices sont simples à inverser : les matrices diagonales, les matrices
triangulaires (par descente ou remontée), les matrices unitaires (il
suffit de les transposer). Pour les matrices plus compliquées, on
cherche à se ramener à une combinaison multiplicative des cas
précédents. On parle de factorisation.

On considère le système
${\mathbf{A}}{\mathbf{x}}={\mathbf{b}}$
dans $\mathbb{E}^n$.

## Systèmes triangulaires

Les matrices triangulaires supérieures ou inférieures inversibles
forment un groupe pour la multiplication. La résolution d'un système
triangulaire est très simple (par descente ou remontée) et de complexité
$O(n^2)$. Remarquons dès à présent qu'il est possible de travailler
simultanément sur un ensemble de seconds membres (matrice rectangulaire
avec relativement peu de colonnes, aussi appelée multivecteur). Le
calcul du déterminant d'une matrice triangulaire est trivial (produit
des coefficients diagonaux).

# Direct Solvers

Direct solvers are based on the observation that three types of
matrices are easy to invert: diagonal matrices, triangular matrices (by descent or
triangular matrices (by descent or ascent), unitary matrices (it is enough to
transpose them). For the more complicated matrices, we try to
try to reduce to a multiplicative combination of the previous cases.
previous cases. This is called factorization.

We consider the system
${\mathbf{A}}{\mathbf{x}}={\mathbf{b}}$
in $\mathbb{E}^n$.

## Triangular systems

Invertible upper or lower triangular matrices
form a group for multiplication. The solution of a triangular system
triangular system is very simple (by descent or ascent) and of complexity
$O(n^2)$. Let us note now that it is possible to work
simultaneously on a set of second members (rectangular matrix
with relatively few columns, also called multivector). The
determinant of a triangular matrix is trivial (product of
of the diagonal coefficients).

Translated with www.DeepL.com/Translator (free version)

Concernant les problèmes de précision, on introduit le nombre
$\gamma_n = n\times u/(1-n\times u)$ (on rappelle que $u$ est l'erreur d'arrondi) qui est très proche de $n\times u$ sauf si la taille du
système devient colossale. On note $|{\mathbf{A}}|$ la
matrice obtenue en appliquant la valeur absolue (le module) à chacune
des composante de ${\mathbf{A}}$.

On peut contrôler l'erreur rétrograde sous la forme
$|\Delta{\mathbf{A}}|\leqslant \gamma_n |{\mathbf{A}}|$.

Concernant l'erreur directe, on a :
$$||\Delta x||_\infty/  \|x\|_\infty \leqslant \operatorname{cond}(T,x)\gamma_n /(1-\kappa_\infty(T) \gamma_n)$$
où
$\operatorname{cond}(T,x)= \frac{\||T^{-1}|\,|T|\,|x|\|_\infty}{\|x\|_\infty}\leqslant\kappa_\infty(T)$.


Concerning the precision problems, we introduce the number
$gamma_n = ntimes u/(1-ntimes u)$ (recall that $u$ is the rounding error) which is very close to $ntimes u$ unless the size of the system
system becomes colossal. We note $|{{mathbf{A}}|$ the
matrix obtained by applying the absolute value (the modulus) to each
of the components of ${{mathbf{A}}}$.

We can control the backward error in the form
$|Delta{\mathbf{A}}|leqslant \gamma_n |{\mathbf{A}}|$.

Concerning the direct error, we have:
$$||Delta x||_\infty/ \|x||_\infty \leqslant \operatorname{cond}(T,x)\gamma_n /(1-\kappa_\infty(T) \gamma_n)$$
where
$$operatorname{cond}(T,x)=$frac{||T^{-1}||,|T||,|x||_\infty}{\x\|_\infty}{\leqslant\kappa_\infty(T)$.


Translated with www.DeepL.com/Translator (free version)

## Méthode de Gauss et méthodes dérivées

### Gauss

Le principe de la méthode de Gauss est de trouver
${\mathbf{M}}$ triangulaire telle que
${\mathbf{M}}{\mathbf{A}}{\mathbf{x}}={\mathbf{U}}{\mathbf{x}}={\mathbf{M}}{\mathbf{b}}$
avec ${\mathbf{U}}$ triangulaire supérieure. C'est une
méthode extrêmement générale, elle fait intervenir deux types de matrices.

    
-   matrices de permutation de ligne :

$${\mathbf{T}}_{i,j} = \begin{pmatrix}
 1 & & & & & & \\ 
 & 1 & & & & &\\
 & & 0_{ii} & \cdots & \cdots & 1_{ij} & \\
 & & \vdots & 1 & & \vdots & \\
 & & \vdots & & 1 & \vdots & \\
 & & 1_{ji} &\cdots&\cdots& 0_{jj} & \\
 & & & & & & 1
 \end{pmatrix}$$
        
Ces matrices ont un déterminant de $(-1)$. Par convention on pose ${\mathbf{T}}_{i,i}={\mathbf{I}}$ dont le déterminant est 1.

-   matrices d'élimination de colonne :

$$\text{si } {\mathbf{A}}=
        \begin{pmatrix}
        a_{11} & a_{12} &        &  \cdots    &        & a_{n1}  \\ 
        0      & \ddots &        &            &        & \vdots  \\
        & \ddots & \ddots &            &        & \vdots  \\
        \vdots &        & 0      & a_{jj}     & \cdots & a_{jn}  \\
        &        & \vdots & \vdots     &        & \vdots  \\
        0     &        & 0      & a_{nj}     & \cdots & a_{nn} 
        \end{pmatrix} \qquad
        \text{avec }a_{jj}\neq 0$$
        
$$\text{on pose }\gamma_{ij} = -a_{ij}/a_{jj} 
        \qquad
        \text{ soit } {\mathbf{E}}_j = \begin{pmatrix}
        1      &    0     &  \cdots    &        & &0 \\ 
        0      &  \ddots  &  \ddots  &        & &  \\
        \vdots &   0     &  1_{jj}    &        &  & \\
        &  \vdots & \gamma_{(j+1)j} & \ddots &  & \\
        &   \vdots & \vdots         &    0    & \ddots& 0\\
        0     &    0    & \gamma_{nj} &    0    &  0    &1 
        \end{pmatrix}$$

Alors ${\mathbf{E}}_j {\mathbf{A}}$ est une
matrice dont on a recombiné les lignes $(j+1)$ à $n$ pour faire
disparaître les coefficients inférieurs de la colonne $j$. Les matrices
${\mathbf{E}}_j$ ont un déterminant de $1$. En itérant on
construit :
$${\mathbf{M}}={\mathbf{E}}_{n-1}{\mathbf{T}}_{n-1}\cdots{\mathbf{E}}_{2}{\mathbf{T}}_{2}{\mathbf{E}}_{1}{\mathbf{T}}_{1}, \ \text{et alors }  {\mathbf{M}}{\mathbf{A}} = {\mathbf{U}}$$
Le rôle des matrices de permutation est de s'assurer que le pivot
$a_{ii}$ est non nul. Si tous ces coefficients sont nuls la matrice
n'est pas inversible (on verra plus loin comment obtenir alors une base
du noyau et une pseudo-inverse). Comme la matrice
${\mathbf{M}}$ a un déterminant de $\pm 1$ (suivant la parité
du nombre de pivotement), on a très simplement le déterminant de
${\mathbf{A}}$ égal au signe près à celui de
${\mathbf{U}}$.

Numériquement, il est conseillé de toujours prendre le plus grand
coefficient disponible comme pivot. On distingue les stratégies de pivot
partiel où l'on va chercher le coefficient sur la colonne $j$ (ligne $j$
à $n$) et les stratégies de pivot total où l'on va aussi chercher parmi
les coefficients sur la ligne $j$ (colonne $j$ à $n$). Le pivot total
revient à s'autoriser à multiplier la matrice à droite ce qui
complexifie légèrement la méthode (surtout sa mise en œuvre).


Pour calculer complètement l'inverse, on peut utiliser la transformation
de Gauss-Jordan :
$$\text{ soit } {\mathbf{\hat{E}}}_j = \begin{pmatrix}
1      &       & 0 & \gamma_{1j}    &    0    & &0 \\ 
0      &  \ddots & & \vdots       &        & & \\ 
&  \ddots & \ddots &  \gamma_{(j-1)j}  &        & &  \\
\vdots &         & 0&  1_{jj}    &   0     &  & \\
&  &\vdots & \gamma_{(j+1)j} & \ddots &  & \\
&   &\vdots & \vdots         &    0    & \ddots& 0\\
0     &        & 0& \gamma_{nj} &    0    &  0    &1 
\end{pmatrix}$$ qui élimine entièrement la colonne $j$ (sauf le terme
diagonal).

La méthode du pivot de Gauss a une complexité en $O(n^3)$ sans compter
la recherche des pivots qui n'est pas une opération de calcul mais une
succession de conditions (qui ne correspondent pas au même type
d'optimisations matérielles et logicielles).


On peut comparer cette méthode à la méthode de Cramer qui donne la solution d'un système sous forme de quotients de déterminants. Pour appliquer la méthode de Cramer, il faut effectuer le calcul de $det(A)$, puis les calculs successifs de :

$x_{1}=det(bA_{2}\ldots A_{n})/det(A)$ avec $A_{i}$ la $i^{eme}$ colonne de la matrice $A$. 

$x_{2}=det(A_{1}bA_{3}\ldots A_{n})/det(A)$

$\vdots$

$x_{n}=det(A_{1}A_{1}\ldots A_{n-1}b)/det(A)$

Essayons d'estimer le temps de calcul associé à cette résolution. Le nombre d'opérations nécessaires pour le calcul d'un déterminant est donné par la formule suivante : $det(A)=\sum_{k=1}^{n} (-1)^{k}\prod_{i=1}^{n} a_{i,k(i)} \qquad \mbox{$k$ : nombre de permutations}$

On obtient donc $(n-1)n!$ multiplications et $n!-1$ additions. Le nombre d'opérations est donc de l'ordre de grandeur de $(n+1)!$. En évaluant la valeur de $n!$ par la formule de Stirling ($n!\sim n^{n+1/2}e^{-n}\sqrt{2\pi}$), pour un système de dimension 100x100, on obtient $\sim$10$^{160}$ opérations à effectuer.

Le plus puissant supercalculateur en novembre 2022 est le Frontier - HPE Cray EX235a de l'Oak Ridge National Laboratory dans le Tenessee aux USA avec 8 730 112 cœurs. Il possède une puissance de calcul de 1102 Exaflop/s (le seul calculateur exaflopique : 1.102 Exaflop/s), soit un peu plus de $10^{21}$ opérations par seconde. Sachant qu'une année comprend $3.10^{7}$ s on obtient pour un système $100\times100$ un temps de calcul de $10^{132}$ années soit $10^{120}$ fois l'âge de l'univers !!! Alors qu'avec une méthode adéquate le même calcul peut prendre moins d'une seconde. Pour la méthode de Gauss, il faut seulement $\sim10^{6}$ opérations (et ce n'est pas la plus efficace).

On propose de programmer la mathode de Gauss, on cherchera le plus grand pivot uniquement sur les colonnes de la matrice.

In [1]:
import numpy as np
from numpy import linalg as la


n=100
# A est une matrice symétrique, définie et positive
A = np.random.random((n, n))
A=A*A.transpose()+n*np.identity(n)
# b est le second membre
b = np.random.random((n,1))

x1 = la.solve(A,b.flatten())

def gauss_elimination(A, b):
    n = len(A)

    for i in range(n):
        # Find pivot
        max_row = i
        for j in range(i + 1, n):
            if abs(A[j][i]) > abs(A[max_row][i]):
                max_row = j

        # Swap rows
        A[i], A[max_row] = A[max_row], A[i]
        b[i], b[max_row] = b[max_row], b[i]

        # Eliminate
        for j in range(i + 1, n):
            factor = A[j][i] / A[i][i]
            b[j] -= factor * b[i]
            for k in range(n):
                A[j][k] -= factor * A[i][k]

    # Back substitution
    x = [0 for _ in range(n)]
    for i in range(n - 1, -1, -1):
        x[i] = b[i]
        for j in range(i + 1, n):
            x[i] -= A[i][j] * x[j]
        x[i] /= A[i][i]
    return x


res = gauss_elimination(A,b)




### Factorisation LU

Dans certains cas, il est possible de ne pas pivoter et d'obtenir
directement ${\mathbf{M}}^{-1}={\mathbf{L}}$, on a
alors la factorisation
${\mathbf{A}}={\mathbf{L}}{\mathbf{U}}$
de la matrice (pour que la factorisation soit unique, on impose que la
matrice ${\mathbf{L}}$ soit à diagonale unitaire). La
condition de non-nécessité de pivotement est que tous les
sous-déterminants soient non-nuls.

La condition ne garantit pas que les pivots naturels soient les
meilleurs (les plus gros des coefficients disponibles), et il est plus
prudent de pivoter malgré tout. Les matrices à diagonale dominante font
exceptions puisque leurs pivots naturels sont automatiquement les plus
gros coefficients disponibles.

Dans le cas tridiagonal, le calcul est particulièrement simple et la
complexité devient de l'ordre de $n$. Les systèmes rectangulaires à
sous-déterminants non-nuls peuvent aussi être factorisés sous forme LU
($\mathbf{L}$ ou $\mathbf{U}$ est de la même forme que $\mathbf{A}$
tandis que l'autre matrice est carrée).

Une variante de la factorisation LU est la factorisation LDU où
$\mathbf{L}$ est triangulaire inférieur à diagonale unitaire,
${\mathbf{D}}$ est diagonale et ${\mathbf{U}}$
triangulaire supérieure à diagonale unitaire. Une telle variante permet
de mettre en exergue les éléments diagonaux (qui doivent être inversés
lors d'une résolution) pour traiter un éventuel problème mal posé.

Concernant la précision de la factorisation, on a le résultat suivant
sur l'erreur rétrograde :
$|\Delta {\mathbf{A}}|  \leqslant \gamma_{3n}/(1-\gamma_n) |{\mathbf{A}}|$.

On propose d'implémenter le calcul d'une décomposition LU.


In [59]:
import numpy as np
from scipy import linalg as lina

n=50
# A est une matrice symétrique, définie et positive
A = np.random.random((n, n))
A=A*A.transpose()+n*np.identity(n)

P, L1, U1 = lina.lu(A)

def lu_decomposition(A):
    n = len(A)
    L = np.eye(n)
    U = A.copy()
    
    for i in range(n):
        for j in range(i+1,n):
            L[j][i] = U[j][i]/U[i][i]
            U[:][j] = U[:][j] - L[j][i]*U[:][i]
            
    return L, U


L2, U2 = lu_decomposition(A)

print("L same:", np.allclose(L1, L2, 1e-6))
print("R same:", np.allclose(U1, U2, 1e-6))

L same: True
R same: True


### Factorisation de Crout

Si la matrice est LU-factorisable et qu'elle est symétrique, elle
peut-être factorisée sous la forme de Crout :
${\mathbf{A}}={\mathbf{L}}{\mathbf{D}}{\mathbf{L}}^T$
avec ${\mathbf{D}}$ diagonale et ${\mathbf{L}}$
triangulaire inférieure à diagonale unitaire. Il est toujours recommandé
de pivoter pour diminuer les erreurs d'arrondi, dans ce cas là il est
nécessaire d'utiliser un pivot symétrique (multiplication à gauche par
${\mathbf{T}}_{ij}$ et à droite par
${\mathbf{T}}_{ij}^T={\mathbf{T}}_{ij}$).

### Factorisation de Cholesky

Si la matrice est symétrique définie positive alors elle peut être
factorisée sous la forme
${\mathbf{A}}={\mathbf{L}}{\mathbf{L}}^T$.
On rappelle au passage qu'une matrice SPD a tous ses sous-déterminants
strictement positifs.

Le nombre d'opérations est approximativement deux fois plus petit que
pour une factorisation LU.

La factorisation de Cholesky a déjà été implémentée dans le chapitre 1. On en redonne pour mémoire un code ci-dessous.  


In [3]:
import numpy as np

n = 50
# A est une matrice symétrique, définie et positive
A = np.random.random((n, n))
A=A*A.transpose()+n*np.identity(n)


## Orthogonalisation QR

Dans le cas d'une matrice carrée, la factorisation QR permet d'écrire
une matrice ${\mathbf{A}}$ sous la forme du produit d'un
matrice unitaire ${\mathbf{Q}}$ et d'une matrice triangulaire
supérieure ${\mathbf{R}}$.

Dans le cas d'une matrice rectangulaire on peut au choix obtenir
${\mathbf{Q}}$ unitaire $m\times m$ et
${\mathbf{R}}$ triangulaire supérieure $m\times n$ ou alors
${\mathbf{Q}}$ $m\times n$ avec des colonnes (si $m>n$) ou
des lignes (si $m<n$) orthonormales entre elles et
${\mathbf{R}}$ triangulaire supérieure $n\times n$. Une
application typique de cette factorisation est donc le calcul du rang
d'une famille de vecteurs. On verra également qu'elle permet la
résolution de problèmes au sens des moindres carrés. Pour les
illustrations à venir on supposera la matrice carrée ou rectangulaire
avec $n>m$ (cas assez récurent de la manipulation d'un petit paquet de
très grands vecteurs).

On peut fournir plusieurs théorèmes d'orthogonalisation. On donne
celui-ci : si ${\mathbf{A}}$ est une matrice carrée d'ordre
$n$, il existe une matrice unitaire ${\mathbf{Q}}$ et une
matrice triangulaire ${\mathbf{R}}$ telles que
${\mathbf{A}}={\mathbf{Q}}{\mathbf{R}}$.
On peut de plus s'arranger pour que tous les éléments diagonaux de
${\mathbf{R}}$ soient positifs (ou nuls). Si
${\mathbf{A}}$ est inversible, la factorisation est alors
unique.

### Version Gram-Schmidt

L'orthogonalisation la plus simple est celle de Gram-Schmidt, elle
consiste à enchainer les manipulations de colonnes de la matrice. On
pose et $r_{11}=\|{\mathbf{a}}_1\|_2$ et
${\mathbf{q}}_1={\mathbf{a}}_1/r_{11}$, si on
suppose avoir construit les $k$ premières colonnes de
${\mathbf{Q}}$ et le bloc $k\times k$ de
${\mathbf{R}}$ tels que $$\begin{pmatrix} 
\vdots & \vdots& \vdots \\
{\mathbf{a}}_1, &\vdots  & {\mathbf{a}}_k \\
\vdots &\vdots & \vdots 
\end{pmatrix}=\begin{pmatrix} 
\vdots & \vdots& \vdots \\
{\mathbf{q}}_1, &\vdots  & {\mathbf{q}}_k \\
\vdots &\vdots & \vdots 
\end{pmatrix} \begin{pmatrix}
r_{11} & \cdots & r_{1k} \\
0 & \ddots & \vdots \\
0 & 0 & r_{kk}
\end{pmatrix} \qquad \text{avec } {\mathbf{q}}_i^H  {\mathbf{q}}_j = \delta_{ij}$$
on calcule : $$\begin{aligned}
&\text{pour }i=1\cdots k\quad r_{i(k+1)} = {\mathbf{q}}_i^H {\mathbf{a}}_{k+1} \\ 
&{\mathbf{q}}_{k+1} = {\mathbf{a}}_{k+1} - \sum_i r_{i(k+1)}{\mathbf{q}}_i \\
& r_{(k+1)(k+1)} = \|{\mathbf{q}}_{k+1}\|\\
&{\mathbf{q}}_{k+1} \leftarrow  {\mathbf{q}}_{k+1} / r_{(k+1)(k+1)} 
\end{aligned}$$ L'algorithme présenté ici est dit de Gram-Schmidt
classique, il peut s'écrire avantageusement sous forme de produits de
sous-blocs de matrice et est donc facilement optimisable (du point de
vue exécution sur un ordinateur). Par contre l'algorithme n'est pas
stable. Si ${\mathbf{Q}}$ et ${\mathbf{R}}$ sont
les matrices obtenues, on a
$\|{\mathbf{A}}-{\mathbf{Q}}{\mathbf{R}}\|$
petit, mais
$\|{\mathbf{Q}}^T{\mathbf{Q}}-{\mathbf{I}}\|$
devient rapidement grand, autrement dit on perd l'orthogonalité. Cela
pose problème si l'on veut se servir de la factorisation pour résoudre
un système

Pour résoudre ce problème, on peut utilisée l'algorithme de Gram-Schmidt
modifié, beaucoup plus stable (en fait très proche de Householder
présenté plus bas) mais beaucoup plus coûteux : $$\begin{aligned}
& {\mathbf{q}}_{k+1} = {\mathbf{a}}_{k+1}\\
&\text{pour }i=1..(k+1)\quad r_{i(k+1)} = {\mathbf{q}}_i ^H {\mathbf{q}}_{k+1}, \quad {\mathbf{q}}_{k+1} \leftarrow {\mathbf{q}}_{k+1}-  r_{i(k+1)}{\mathbf{q}}_i \\
& r_{(k+1)(k+1)} = \|{\mathbf{q}}_{k+1}\|\\
&{\mathbf{q}}_{k+1}  \leftarrow {\mathbf{q}}_{k+1} / r_{(k+1)(k+1)}
\end{aligned}$$ Même améliorée, la méthode de Gram-Schmidt est simple à
coder, à optimiser et surtout permet d'accéder à
${\mathbf{Q}}$ (si seul ${\mathbf{R}}$ est
recherché Householder est plus rapide).


In [73]:
import numpy as np

n = 3
# A est une matrice symétrique, définie et positive
A = np.random.random((n, n))
A=A*A.transpose()+n*np.identity(n)

def modified_gram(A):
    n = A.shape[0]
    r = np.eye(n)
    q = np.zeros((n,n))
    v = np.zeros((n,n))
    for i in range(n):
        v[:][i] = A[:][i]
    for i in range(n):
        r[i][i] = la.norm(v[:][i],2)
        q[:][i] = v[:][i]/r[i][i]
        for j in range(i+1, n):
            r[i][j] = q[:][i]@v[:][j]
            v[:][j] = v[:][j] - r[i][j]*q[:][i]

    return q,r

q,r = modified_gram(A)
print(q)
print(r)


    


[[ 0.9972901   0.05245861  0.05158058]
 [-0.05429321  0.99791727  0.03483332]
 [-0.04964585 -0.0375394   0.99806116]]
[[3.8279314  0.41179134 0.36220533]
 [0.         3.8654458  0.25094528]
 [0.         0.         3.02446696]]


In [82]:
import numpy as np

n = 3
# A est une matrice symétrique, définie et positive
A = np.random.random((n, n))
A=A*A.transpose()+n*np.identity(n)

def modified_gram(A):
    n = A.shape[0]
    r = np.eye(n)
    q = np.zeros((n,n))
    v = np.zeros((n,n))
    for k in range(n):
        q[k] = A[k]
        for i in range(k-1):
            r[i][k] = q[i].T@q[k]
            q[k] = q[k] - r[i][k]*q[i]
        r[k][k] = la.norm(q[k],2)
        q[k] = q[k]/r[k][k]
        

    return q,r

q,r = modified_gram(A)
print(q)
print(r)


    


[[ 0.98441421  0.17549506  0.0114085 ]
 [ 0.1991429   0.96843955  0.14988975]
 [-0.03619378  0.13868754  0.98967458]]
[[3.52565988 0.         0.15701557]
 [0.         3.10699446 0.        ]
 [0.         0.         3.15926839]]


In [81]:
import numpy as np

n = 3
# A est une matrice symétrique, définie et positive
A = np.random.random((n, n))
A=A*A.transpose()+n*np.identity(n)

def modified_gram_schmidt(vectors):
    # Obtain the number of vectors
    n = len(vectors)

    # Initialize the list of orthonormal basis vectors and the r_matrix with zeros
    orthonormal_basis = []
    r_matrix = np.zeros((n, n))

    # Iterate over the vectors
    for i in range(n):
        # Set the current vector to be the i-th vector
        v = vectors[i]

        # Subtract the projection of v onto the subspace spanned by the previous vectors
        for j in range(i):
            r = orthonormal_basis[j] @ v
            v = v - r * orthonormal_basis[j]
            r_matrix[j][i] = r

        # Normalize v and add it to the list of orthonormal basis vectors
        v = v / np.linalg.norm(v)
        orthonormal_basis.append(v)
        r_matrix[i][i] = np.linalg.norm(v)

    # Return the orthonormal basis and the r_matrix
    return orthonormal_basis, r_matrix

q,r = modified_gram_schmidt(A)
print(q)
print(r)
print(A)
print(A[1])

[array([0.99569753, 0.05373748, 0.07548982]), array([-0.05788115,  0.99687179,  0.05381834]), array([-0.0723616 , -0.05795623,  0.99569316])]
[[1.         0.38856772 0.55150358]
 [0.         1.         0.34475917]
 [0.         0.         1.        ]]
[[3.96363727 0.21391626 0.30050717]
 [0.21391626 3.00006374 0.19017074]
 [0.30050717 0.19017074 3.20665818]]
[0.21391626 3.00006374 0.19017074]


### Version Householder

L'intérêt de la méthode de Householder est de faire intervenir des
transformations unitaires dont on a vu qu'elles ne dégradaient pas le
conditionnement $\kappa_2$. Elle est donc réputée beaucoup plus stable
qu'une technique de Gauss pour résoudre un système mais elle fait
intervenir environ deux fois plus d'opérations. La méthode repose sur
l'emploi des matrices de réflexion dites de Householder.

On appelle matrice de réflexion de Householder la matrice $n\times n$
${\mathbf{H}}$ :
$${\mathbf{H}}_{{\mathbf{v}}} = {\mathbf{I}}-2\frac{{\mathbf{v}}{\mathbf{v}}^H}{{\mathbf{v}}^H{\mathbf{v}}}$$
${\mathbf{v}}$ est le vecteur de Householder.
${\mathbf{P}}$ est unitaire et hermitienne, elle réalise une
réflexion par rapport à l'hyperplan
${\operatorname{vect}}({\mathbf{v}})^\perp$. Cette
matrice est obtenue à partir de l'identité à l'aide d'une perturbation
de rang 1.

Le théorème utile est le suivant : Soit ${\mathbf{a}}$ un
vecteur de ${\mathbb{C}}^n$ tel que $a_1\neq 0$ et
$\sum_{i=2}^n|a_i|>0$. Il existe deux matrices de Householder
${\mathbf{H}}$ telles que les $(n-1)$ dernières composantes
du vecteur ${\mathbf{H}}{\mathbf{a}}$ soit nulles.
De façon plus précise, soit $\alpha\in {\mathbb{R}}$ tel que
$a_1 = e^{i\alpha}|a_1|$, alors si ${\mathbf{e}}_1$ est le
premier vecteur de base de ${\mathbb{C}}^n$:
$${\mathbf{H}}_{({\mathbf{a}}+\|{\mathbf{a}}\|_2 e^{i\alpha} {\mathbf{e}}_1)} {\mathbf{a}} =- \|{\mathbf{a}}\|_2 {\mathbf{e}}_1,\qquad {\mathbf{H}}_{({\mathbf{a}}-\|{\mathbf{a}}\|_2 e^{i\alpha} {\mathbf{e}}_1)} {\mathbf{a}} = \|{\mathbf{a}}\|_2 {\mathbf{e}}_1$$

En pratique, on calcule $\|{\mathbf{a}}\|_2$ puis
${\mathbf{v}}=({\mathbf{a}} \pm \|{\mathbf{a}}\|_2 e^{i\alpha} {\mathbf{e}}_1)$
et le nombre
$\frac{{\mathbf{v}}^H{\mathbf{v}}}{2}=\|{\mathbf{a}}\|_2(\|{\mathbf{a}}\|_2\pm |a_1|)$.
Le calcul de l'image d'un vecteur ${\mathbf{x}}$ se fait de
la façon suivante :
$${\mathbf{H}}_v{\mathbf{x}} = {\mathbf{x}}-\frac{{\mathbf{v}}^H{\mathbf{x}}}{{\mathbf{v}}^H{\mathbf{v}}/2}{\mathbf{v}}$$
Dans le cas réel le *signe est choisi* de manière à éviter un
dénominateur trop petit donc on prend
${\mathbf{v}}=({\mathbf{a}} +{\operatorname{signe}}(a_1) \|{\mathbf{a}}\|_2 {\mathbf{e}}_1)$.

La méthode de Householder consiste donc à calculer
${\mathbf{A}}_k={\mathbf{H}}_{k-1}\cdots{\mathbf{H}}_1{\mathbf{A}}$
avec : $${\mathbf{A}}_k = 
\begin{pmatrix}
\times & \times & \times & \times & \times & \times    \\
& \times & \times & \times & \times & \times  \\
&        & \times_{kk} & \times & \times & \times  \\
&        & \times & \times & \times & \times  \\
&        & \times & \times & \times & \times  \\
&        & \times_{nk} & \times & \times & \times  \\
\end{pmatrix}$$ 

Si besoin on pratique une permutation de lignes
(permutation à droite) de manière à rendre le coefficient $kk$ non-nul.
On extrait de ${\mathbf{A}}_k$ le vecteur
$\tilde{{\mathbf{a}}}_k$ de dimension $(n-k+1)$ de
coefficients $a_{ik}$ $(k\leqslant i \leqslant n)$. On choisit le
vecteur $\tilde{{\mathbf{v}}}_k$ tel que
${\mathbf{H}}_{\tilde{{\mathbf{v}}}_k}{\mathbf{v}}_k$
ait toutes ses composantes nulles sauf la première et on pose :
$${\mathbf{H}}_k = 
\begin{pmatrix}
{\mathbf{I}}_{k-1} & {\mathbf{0}} \\ {\mathbf{0}} & {\mathbf{H}}_{\tilde{{\mathbf{v}}}_k}
\end{pmatrix}$$

Il est possible de représenter le produit de $r$ matrices de Householder
sous forme bloc :
$${\mathbf{Q}}={\mathbf{I}}+{\mathbf{W}}{\mathbf{Y}}^H$$
où ${\mathbf{W}}$ et ${\mathbf{Y}}$ sont des
matrices $n\times r$. Le mécanisme est le suivant :
$${\mathbf{Q}}{\mathbf{H}}_{{\mathbf{v}}}={\mathbf{I}}+\begin{pmatrix}{\mathbf{W}},& -\frac{2}{{\mathbf{v}}^H{\mathbf{v}}}{\mathbf{Q}}{\mathbf{v}}\end{pmatrix}\begin{pmatrix}{\mathbf{Y}},& {\mathbf{v}}\end{pmatrix}^H$$


### Version Givens

A l'instar de Householder, l'orthogonalisation de Givens fait intervenir
des transformations unitaires et donc ne détériore pas le
conditionnement $\kappa_2$. La méthode repose sur l'emploi des matrices
de rotations dites de Givens qui sont des perturbations de rang 2 de
l'identité. Ces matrices permettent d'intervenir plus spécifiquement sur
certains coefficients d'une matrice. Par simplicité, on se place dans
${\mathbb{R}}$. On pose :
$${\mathbf{G}}_{ij}(\theta)=\begin{pmatrix}
{\mathbf{I}}_{i-1} &             &    &   &{\mathbf{0}} \\
& \cos(\theta)_{ii}   &     {\mathbf{0}}        &  \sin(\theta)_{ij} &    \\
&  {\mathbf{0}}   & {\mathbf{I}}_{n-2} &  {\mathbf{0}}  &    \\
& -\sin(\theta)_{ji}  &      {\mathbf{0}}       & \cos(\theta)_{jj}  &    \\
{\mathbf{0}}     &     &             &    & {\mathbf{I}}_{n-j} \\ 
\end{pmatrix}$$ Si on calcule le produit suivant :
$${\mathbf{Y}}={\mathbf{G}}_{ik}(\theta)^T {\mathbf{X}} ;\qquad y_{qr} = \left\{
\begin{array}{lr} 
\cos(\theta)x_{ir}-\sin(\theta)x_{jr} & q=i,\ \forall r \\
\sin(\theta)x_{ir}+\cos(\theta)x_{jr} & q=j,\ \forall r \\
x_{qr} & q\neq i,j,\ \forall r  \\
\end{array}\right.$$ L'idée derrière cela est de calculer $\theta$ pour
annuler des coefficients. Par exemple si on veut annuler $y_{qr}$ (ici
les deux indices sont fixés), on prend $i$ tel que $x_{ir}\neq 0$ et on
pose
$$\cos(\theta) = \frac{x_{ir}}{\sqrt{x_{ir}^2+x_{qr}^2}}, \qquad \sin(\theta) = \frac{x_{qr}}{\sqrt{x_{ir}^2+x_{qr}^2}}$$


Si on cherche à minimiser les erreurs d'arrondi, alors si $a$ et $b$ sont donnés et que
l'on cherche $c=\cos(\theta)$ et $s=\sin(\theta)$ tels que
$$\begin{pmatrix}
c & s \\ -s & c
\end{pmatrix}^T \begin{pmatrix} a \\b \end{pmatrix} = \begin{pmatrix} r \\ 0 \end{pmatrix}$$
alors $$\begin{array}{ll}
\text{si }b=0, & c=1,\ s=0 \\
\text{si }|b|>|a|, & \tau=-a/b,\ s=1/\sqrt{1+\tau^2},\ c=s\tau \\
\text{si }|b|\leqslant|a|, & \tau=-b/a,\ c=1/\sqrt{1+\tau^2},\ c=c\tau 
\end{array}$$

Une utilisation typique des rotations de Givens (le tilde indique une
modification du coefficient d'une étape à l'autre) : $$\begin{pmatrix}
\times & \times & \times \\
\times & \times & \times \\
\times & \times & \times 
\end{pmatrix} \xrightarrow{(3,1)} 
\begin{pmatrix}
\times & \times & \times \\
\tilde{\times} & \tilde{\times} & \tilde{\times} \\
0      & \tilde{\times} & \tilde{\times} 
\end{pmatrix} \xrightarrow{(2,1)}
\begin{pmatrix}
\tilde{\times} & \tilde{\times} & \tilde{\times} \\
0 & \tilde{\times} & \tilde{\times} \\
0      & \times & \times
\end{pmatrix}\xrightarrow{(3,2)}
\begin{pmatrix}
\times & \times & \times \\
0 & \tilde{\times} & \tilde{\times} \\
0      & 0 & \tilde{\times}
\end{pmatrix}$$ On verra une application typique dans le solveur GMRes
pour résoudre un système de Hessemberg.

On propose de coder la détermination de la décomposition QR : on comparera $\|{\mathbf{Q}}^T{\mathbf{Q}}-{\mathbf{I}}\|$ pour les version Gram-Schmidt et Givens.

In [5]:
from math import hypot
import numpy as np
from numpy import linalg as la

n = 200
# A est une matrice symétrique, définie et positive
A = np.random.random((n, n))
A=A*A.transpose()+n*np.identity(n)

def condit(M,i):
    return la.norm(M,i)*la.norm(la.inv(M),i)



### Factorisation QR et systèmes rectangulaires

Les factorisation QR se prêtent bien au calcul de systèmes
rectangulaires car la préservation de la norme permet de facilement
intégrer les régularisations présentées précédemment.

Si on considère un système sur déterminé
${\mathbf{A}}{\mathbf{x}}={\mathbf{b}}$
avec ${\mathbf{A}}\in{\mathbb{E}}^{m\times n}$ et
$m>n$. On a : $$\begin{aligned}
\left\| {\mathbf{b}}-{\mathbf{A}}{\mathbf{x}}\right\|_2^2 & = \left\| {\mathbf{b}}-\begin{pmatrix}
{\mathbf{Q}}_1 & {\mathbf{Q_2}} 
\end{pmatrix}\begin{pmatrix}
{\mathbf{R}}_1 \\ 0 
\end{pmatrix} \right\|_2^2 \\
&= \left\|\begin{pmatrix}
{\mathbf{Q}}_1^H {\mathbf{b}} - {\mathbf{R}}_1 {\mathbf{x}} \\ {\mathbf{Q}}_2^H {\mathbf{b}} 
\end{pmatrix}\right\|_2^2 =  \left\|{\mathbf{Q}}_1^H {\mathbf{b}} - {\mathbf{R}}_1 {\mathbf{x}}\right\|_2^2 +\left\|{\mathbf{Q}}_2^H {\mathbf{b}}\right\|_2^2 
\end{aligned}$$ où l'on voit que le minimum est égal à
$\left\|{\mathbf{Q}}_2^H {\mathbf{b}}\right\|_2^2$
(qui mesure l'écart du second membre à l'image de
${\mathbf{A}}$) et est atteint pour
${\mathbf{R}}_1 {\mathbf{x}} = {\mathbf{Q}}_1^H {\mathbf{b}}$
(petit système triangulaire).

Concernant les systèmes sous-déterminés $m<n$, on peut utiliser la
factortisation $QR$ de ${\mathbf{A}}^T$. On a :
$$\begin{aligned}
{\mathbf{A}}{\mathbf{x}} & = {\mathbf{b}}\\
{\mathbf{R^T}}{\mathbf{Q}}^T{\mathbf{x}}&={\mathbf{b}}
\end{aligned}$$ Si on cherche ${\mathbf{x}}$ sous la forme
${\mathbf{Q}}{\mathbf{y}}+{\mathbf{z}}$
avec ${\mathbf{Q}}^T{\mathbf{z}}=0$, on a
$\|{\mathbf{x}}\|^2_2 = \|{\mathbf{y}}\|^2_2 + \|{\mathbf{z}}\|^2_2$.
Donc
${\mathbf{x}}={\mathbf{Q}}{\mathbf{R}}^{-T}{\mathbf{b}}$
est la solution de norme minimale.
